#!/bin/bash

VIMRC=$TMPDIR/mini-vimrc
SOURCE=$(dirname $BASH_SOURCE)/..

cat > $VIMRC << EOF
set nocompatible
syntax on

for dep in ['vader.vim', 'vim-alt-mappings']
  execute 'set rtp+=' . finddir(dep, expand('~/.vim').'/**')
endfor
set rtp+=$SOURCE

nnoremap Q :qa!<CR>
EOF

vim -u $VIMRC "+Vader! **/*.vader"

rm -f $VIMRC
